language: cpp
sudo: required
dist: bionic

compiler:
- clang
- gcc
os:
- linux

ruby: 2.2.0
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then ./ci/dependencies_linux.sh; fi
- if [ $TRAVIS_OS_NAME == osx ]; then ./ci/depencencies_osx.sh;
